### ISSUE TITLE
Plug-ins do not work on iOS

### ISSUE THREAD

**Issue by Volcsamp** [benwiley4000/volca-sampler#119]
When installing and running plug-ins on iOS, we get an error flag and a request to reload the plugin. Reloading does not fix the issue.

![IMG_0634](https://github.com/benwiley4000/volca-sampler/assets/159139986/7d67b9ba-1d01-49da-8225-2fa9685fc7ad)

This behaviour was repeated on chrome iOS, safari and Firefox on an iPad 8 and iPhone 15

Checking the JavaScript console logs through chrome, it outputs

![IMG_0633](https://github.com/benwiley4000/volca-sampler/assets/159139986/ac550fbd-e75c-4738-a22a-c74972cc6d83)

errorreferenceerror:%20Can't%20find%20variable%3A%20mutex

**Comment by benwiley4000** [comment]
Thanks so much for the detailed error report. Also thank you for sharing the JavaScript console screenshot. I didn't know you could do this on iOS, very useful.

For future reference, Chrome and Firefox are running the same browser on iOS (Safari) because Apple doesn't allow third party browsers. So it makes sense all browsers did the same. Could you please share what versions of iOS you're running on your iPad and in your phone?

It appears this person had the same issue. https://stackoverflow.com/questions/49247362/safari-bug-with-block-scoped-variables

I just made a quick fix and deployed it to volcasampler.com. Could you test it for me please?

**Comment by Volcsamp** [comment]
Hi Ben. Thanks for the quick response!

The JavaScript console was something I found while trying to troubleshoot
the issue, I'm happy it could help :)

I figured different browsers wouldn't help as I was aware about the issue
with safari and other browsers on iOS but just thought I'd try in the
spirit of proper bug reporting.

Both devices were running the latest iOS (version 17 I believe) but I can
confirm that when I get home today
I'm not able to test on the exact same devices until after work today
however I did just run a quick test on a separate iOS device (iPhone 11 iOS
version 17) and can confirm that the plugins work as expected so it looks
like that fix has done the trick, again I will check on the original
devices as soon as I can.

Thanks again for your work on this web tool and your continued support of
it. I've just bought a volca sample and am having a bit of a steep learning
curve compared to other volcas I've had in the past. Your web tool is the
only thing that consistently works when it comes to uploading and erasing
samples.

**Comment by benwiley4000** [comment]
I'm so glad to hear that, thanks for helping me about my reporting your
issues! Please let me know if you have any other feedback of any kind.

Ben

Le mar. 6 févr. 2024, 7 h 16 p.m., Volcsamp ***@***.***> a
écrit :

> Hi Ben. Thanks for the quick response!
>
> The JavaScript console was something I found while trying to troubleshoot
> the issue, I'm happy it could help :)
>
> I figured different browsers wouldn't help as I was aware about the issue
> with safari and other browsers on iOS but just thought I'd try in the
> spirit of proper bug reporting.
>
> Both devices were running the latest iOS (version 17 I believe) but I can
> confirm that when I get home today
> I'm not able to test on the exact same devices until after work today
> however I did just run a quick test on a separate iOS device (iPhone 11
> iOS
> version 17) and can confirm that the plugins work as expected so it looks
> like that fix has done the trick, again I will check on the original
> devices as soon as I can.
>
> Thanks again for your work on this web tool and your continued support of
> it. I've just bought a volca sample and am having a bit of a steep
> learning
> curve compared to other volcas I've had in the past. Your web tool is the
> only thing that consistently works when it comes to uploading and erasing
> samples.
>

**Comment by Volcsamp** [comment]
Hey Ben. Just checking in to confirm that the issue is resolved on the
original hardware. I had to clear my cache for it to take effect but I can
now load plugins without issue.

**Comment by benwiley4000** [comment]
Dope! Thank you

**Comment by benwiley4000** [comment]
Hey just wanted to check in, were you able to accomplish what you wanted to with the plugins?

**Comment by Volcsamp** [comment]
Hi Ben.

I'm sorry for the wildly overdue response. I've had a busy month
between family life and transitioning jobs.

Yes the update fixed everything perfectly. Thank you so much for your
prompt response and thorough communication of the changes.

Also thanks once again for making such an awesome web based app that solves
so many problems for volca sampler users.
